[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
rand = "0.8.5"
simplelog = "0.12.2"
simplevm = { path = "../vm" }

[lib]
crate-type = ["lib"]

[[bin]]
name = "lang"
